"""tambah tabel access_entries dan access_entry_fields

Revision ID: 05e4541d4c27
Revises: a656f23abae9
Create Date: 2026-09-25 15:45:20.292643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e4541d4c27'
down_revision = 'a656f23abae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('encrypted_access_note', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=10), server_default='private', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('unknown', 'up', 'down')", name=op.f('ck_access_entries_status_valid')),
    sa.CheckConstraint("visibility IN ('public', 'private')", name=op.f('ck_access_entries_visibility_valid')),
    sa.CheckConstraint('port IS NULL OR (port >= 1 AND port <= 65535)', name=op.f('ck_access_entries_port_valid')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_access_entries_category_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_access_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_entries'))
    )
    with op.batch_alter_table('access_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_entries_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_entries_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_entries_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_entries_user_id'), ['user_id'], unique=False)

    op.create_table('access_entry_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_entry_id', sa.Integer(), nullable=False),
    sa.Column('field_label', sa.String(length=100), nullable=False),
    sa.Column('field_content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['access_entry_id'], ['access_entries.id'], name=op.f('fk_access_entry_fields_access_entry_id_access_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_entry_fields'))
    )
    with op.batch_alter_table('access_entry_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_entry_fields_access_entry_id'), ['access_entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_entry_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_entry_fields_access_entry_id'))

    op.drop_table('access_entry_fields')
    with op.batch_alter_table('access_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_entries_url'))
        batch_op.drop_index(batch_op.f('ix_access_entries_category_id'))
        batch_op.drop_index(batch_op.f('ix_access_entries_address'))

    op.drop_table('access_entries')
    # ### end Alembic commands ###
