"""Tambah tabel attachments

Revision ID: 5e2eea6729bd
Revises: 05e4541d4c27
Create Date: 2026-09-28 09:09:06.622623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2eea6729bd'
down_revision = '05e4541d4c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('file_size > 0', name=op.f('ck_attachments_file_size_positive')),
    sa.ForeignKeyConstraint(['access_entry_id'], ['access_entries.id'], name=op.f('fk_attachments_access_entry_id_access_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attachments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('stored_filename', name=op.f('uq_attachments_stored_filename'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_access_entry_id'), ['access_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_user_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_access_entry_id'))

    op.drop_table('attachments')
    # ### end Alembic commands ###
