"""Tambah tabel groups, group_member, dan group_entries

Revision ID: ead5bf8bec03
Revises: 5e2eea6729bd
Create Date: 2026-09-28 11:45:41.986909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead5bf8bec03'
down_revision = '5e2eea6729bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_groups_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_user_id'), ['user_id'], unique=False)

    op.create_table('group_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('access_entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['access_entry_id'], ['access_entries.id'], name=op.f('fk_group_entries_access_entry_id_access_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_entries_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_entries')),
    sa.UniqueConstraint('group_id', 'access_entry_id', name=op.f('uq_group_entries_group_id'))
    )
    with op.batch_alter_table('group_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_entries_access_entry_id'), ['access_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_entries_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_entries_user_id'), ['user_id'], unique=False)

    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), server_default='member', nullable=False),
    sa.Column('status', sa.String(length=10), server_default='invited', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name=op.f('ck_group_members_role_valid')),
    sa.CheckConstraint("status IN ('invited', 'active')", name=op.f('ck_group_members_status_valid')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_members_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_members')),
    sa.UniqueConstraint('group_id', 'user_id', name=op.f('uq_group_members_group_id'))
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_group_id'))

    op.drop_table('group_members')
    with op.batch_alter_table('group_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_entries_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_entries_access_entry_id'))

    op.drop_table('group_entries')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_user_id'))

    op.drop_table('groups')
    # ### end Alembic commands ###
